volumes:
  site-packages:

configs:
  keria:
    content: |
      {
          "dt": "2023-12-01T10:05:25.062609+00:00",
          "keria": {
              "dt": "2023-12-01T10:05:25.062609+00:00",
              "curls": ["http://keria:3902/"]
          },
          "iurls": [
              "http://witness-demo:5642/oobi/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha/controller",
              "http://witness-demo:5643/oobi/BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM/controller",
              "http://witness-demo:5644/oobi/BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX/controller"
          ]
      }
  keria_launch:
    content: |
      {
          "version": "0.2.0",
          "configurations": [
              {
                  "name": "Python Debugger: Launch Keria",
                  "type": "debugpy",
                  "request": "launch",
                  "console": "integratedTerminal",
                  "module": "keria",
                  "args": [
                      "start",
                      "--config-file",
                      "keria"
                  ]
              }
          ]
      }
  wan:
    content: |
      {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "wan": {
              "dt": "2022-01-20T12:57:59.823350+00:00",
              "curls": ["http://witness-demo:5642/"]
          }
      }
  wil:
    content: |
      {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "wil": {
              "dt": "2022-01-20T12:57:59.823350+00:00",
              "curls": ["http://witness-demo:5643/"]
          }
      }
  wes:
    content: |
      {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "wes": {
              "dt": "2022-01-20T12:57:59.823350+00:00",
              "curls": ["http://witness-demo:5644/"]
          }
      }

services:
  vlei-server:
    image: gleif/vlei
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    command: ["vLEI-server", "-s", "./schema/acdc", "-c", "./samples/acdc/", "-o", "./samples/oobis/"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7723/oobi/EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    ports:
      - 7723:7723

  witness-demo:
    image: weboftrust/keri-witness-demo:1.1.0
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5642/oobi"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    configs:
      - source: wan
        target: /usr/local/var/keri/cf/wan.json
      - source: wes
        target: /usr/local/var/keri/cf/wes.json
      - source: wil
        target: /usr/local/var/keri/cf/wil.json
    ports:
      - 5642:5642
      - 5643:5643
      - 5644:5644

  keria:
    configs:
      - source: keria
        target: /usr/local/var/keri/cf/keria.json
      - source: keria_launch
        target: /home/${USERNAME}/code/keria/.vscode/launch.json
    volumes:
      - ../keria:/home/${USERNAME}/code/keria
      - ../keripy:/home/${USERNAME}/code/keripy
    working_dir: /home/${USERNAME}/code/keria
    build:
      context: .
      args:
        - UID=${UID}
        - USERNAME=${USERNAME}
    command: sleep infinity
    ports:
      - 3901:3901
      - 3902:3902
      - 3903:3903
